### ISSUE TITLE
pip install -r requirements errors 

### ISSUE THREAD

**Issue by d-hoke** [TileDB-Inc/tiledb-benchmarks#4]
ubuntu 18.04 LTS (mostly up-to-date), python 3.6.9, intel Q840, 8GB ram
(Issues with markupsafe==1.0, (nonexistent?) pkg-resources=0.0.0, and numpy==1.14.5)
(in/related to requirements.txt, 
changed to markupsafe==1.1.0, 
removed pkg-resources=0.0.0, 
and manually uninstalled numpy==1.14.5 and installed default at time of install [which happens to be 1.19.2])

`pip install -r requirements.txt`
for me produces

`Collecting MarkupSafe==1.0
  Downloading MarkupSafe-1.0.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /mnt/tiledbdrv/home/dev1/dev/tiledbubuntu18.04/gh.tiledb-benchmarks.git/bcolz-zarr/p3-venv1/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k6fy9aow/markupsafe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-k6fy9aow/markupsafe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-36iaqoob
         cwd: /tmp/pip-install-k6fy9aow/markupsafe/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-k6fy9aow/markupsafe/setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature'
    ----------------------------------------
`

seems other project(s) have (had) a similar issue, one example at
https://stackoverflow.com/questions/62222436/importerror-cannot-import-name-feature-from-setuptools

Or, is bitrot on my side, Ubuntu 18.04 LTS?

https://github.com/pallets/markupsafe/issues/57

Changed requirements.txt to have MarkUpSafe=1.1.0 and got past that, then got
`ERROR: Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 43)) (from versions: none)
ERROR: No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 43))

https://stackoverflow.com/questions/38992194/why-does-pip-freeze-list-pkg-resources-0-0-0`

after removing the 'pkg-resources=0.0.0' from requirements.txt, pip install -r requirements.txt completed.
(now to see if benchmark will run for me :) )

no didn't run, had issue similar to that described at
https://github.com/numpy/numpy/issues/12785

`pip uninstall numpy` to remove the requirements.txt version of 1.14.2
and
`pip install numpy` with no version requirement
and got past that error.
(Think I'm now stuck where it wants to talk to AWS, 
KeyError: 'AWS_ACCESS_KEY_ID'
but I suspect that's not an install problem since I don't have access to AWS.)

**Comment by ihnorton** [comment]
Thanks @d-hoke -- this repository has definitely bitrotted since these benchmarks were run; unfortunately the pip pinning is incomplete (and, in any case, all of the libraries have progressed in the past 2 years). We will take a look at the two issues you raised here this week.

**Comment by d-hoke** [comment]
No particular rush on my part at this point

________________________________
